data:
  candidate_set: "./data/candidate_set_smiles_plus_features.csv"
  finetuning_set: "./data/finetuning_set_smiles_plus_features.csv"

model:
  gnn_variant: "GNN_variant_name"
  hidden_dim: 128
  num_layers: 3
  output_dim: 1

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50